name: flutter_nsd_example
description: Demonstrates how to use the flutter_nsd plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_nsd:
    path: ../

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
