name: flutter_nsd

on:
  push:
  pull_request:
    branches: [master]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: |
          cd example/
          flutter config --enable-windows-desktop
          flutter build windows
        # working-directory: example
      - uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: |
            example/build/windows/runner/Release/
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter pub get
        working-directory: example
      - run: flutter build apk
        working-directory: example
      - uses: actions/upload-artifact@v2
        with:
          name: android-build
          path: |
            example/build/app/outputs/flutter-apk/app-release.apk
  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter pub get
        working-directory: example
      - run: flutter build ios --release --no-codesign
        working-directory: example
      - uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: |
            example/build/ios/iphoneos/Runner.app
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter config --enable-macos-desktop
        working-directory: example
      - run: flutter build macos
        working-directory: example
      - uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: |
            example/build/macos/Build/Products/Release/flutter_nsd_example.app

